[package]
name = "forge-output"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
arboard = { workspace = true }
enigo = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
